import type { Metadata } from "next";
import Reveal from "@/components/Reveal";
import { DATASET, MODEL } from "@/lib/content";
import { EDGE_TYPE_LIST } from "@/lib/edgeTypes";

export const metadata: Metadata = { title: "Methodology — Structure Over Surface" };

export default function MethodologyPage() {
  return (
    <div className="mx-auto max-w-3xl px-5 sm:px-8 py-20 sm:py-28">
      <Reveal>
        <h1 className="font-display text-4xl sm:text-5xl">Methodology</h1>
      </Reveal>

      <Reveal delay={0.05}>
        <p className="measure mt-6 text-text-dim leading-relaxed">
          Three parts: a matched dataset of human and machine-written functions, a graph
          construction step that turns each function into a typed AST graph, and a Graph
          Isomorphism Network trained to tell the two apart from structure alone.
        </p>
      </Reveal>

      <section className="mt-20">
        <Reveal>
          <h2 className="font-display text-2xl">Dataset</h2>
        </Reveal>
        <Reveal delay={0.05}>
          <p className="measure mt-4 text-text-dim leading-relaxed">
            {DATASET.totalPairs} matched Python function pairs: {DATASET.human} written by
            humans, {DATASET.machine} generated by {DATASET.generatorForTraining} for the
            same underlying task. The pairing means every human function has exactly one
            machine counterpart solving the same problem — the model can&apos;t learn to
            distinguish task difficulty instead of authorship.
          </p>
        </Reveal>
        <Reveal delay={0.1}>
          <div className="mt-6 font-mono text-sm text-text-dim border border-border-color divide-y divide-border-color">
            <div className="flex justify-between px-4 py-3">
              <span>Train</span>
              <span className="text-text">{DATASET.train} graphs</span>
            </div>
            <div className="flex justify-between px-4 py-3">
              <span>Validation</span>
              <span className="text-text">{DATASET.val} graphs</span>
            </div>
            <div className="flex justify-between px-4 py-3">
              <span>Test</span>
              <span className="text-text">{DATASET.test} graphs</span>
            </div>
          </div>
        </Reveal>
      </section>

      <section className="mt-20">
        <Reveal>
          <h2 className="font-display text-2xl">Graph construction</h2>
        </Reveal>
        <Reveal delay={0.05}>
          <p className="measure mt-4 text-text-dim leading-relaxed">
            Python&apos;s built-in <code className="font-mono text-text">ast</code> module
            parses each function. Every AST node becomes a graph node, typed by its Python
            class name (<code className="font-mono text-text">FunctionDef</code>,{" "}
            <code className="font-mono text-text">For</code>,{" "}
            <code className="font-mono text-text">If</code>,{" "}
            <code className="font-mono text-text">Call</code>, and so on) through a
            90-entry vocabulary. No identifiers, literal values, or comments are recorded —
            structure only.
          </p>
        </Reveal>
        <Reveal delay={0.1}>
          <div className="mt-8 space-y-4">
            {EDGE_TYPE_LIST.map((e) => (
              <div key={e.key} className="flex gap-4 items-start border-l-2 pl-4" style={{ borderColor: e.color }}>
                <div>
                  <div className="font-mono text-sm" style={{ color: e.color }}>
                    {e.label}
                  </div>
                  <p className="text-sm text-text-dim mt-1 measure">{e.description}</p>
                </div>
              </div>
            ))}
          </div>
        </Reveal>
      </section>

      <section className="mt-20">
        <Reveal>
          <h2 className="font-display text-2xl">Model</h2>
        </Reveal>
        <Reveal delay={0.05}>
          <p className="measure mt-4 text-text-dim leading-relaxed">
            A {MODEL.name} with {MODEL.layers} message-passing layers and{" "}
            {MODEL.hiddenDim} hidden dimensions, pooled by concatenating {MODEL.pooling}{" "}
            global pooling, followed by a binary classification head.
          </p>
        </Reveal>

        <Reveal delay={0.12}>
          <div className="mt-8 border border-edge-flow/40 bg-edge-flow/[0.06] px-5 py-5">
            <p className="font-mono text-xs text-edge-flow mb-2">Disclosed limitation</p>
            <p className="measure text-text-dim leading-relaxed text-[0.95rem]">
              The model&apos;s forward pass only takes node features, edge connectivity,
              and batch assignment — it does <span className="text-text">not</span> read
              edge type. All three edge kinds above pass through identical GIN layers.
              Edge type is stored on the graph and used only for a later
              ablation-by-masking experiment, not by the model that produced the results
              on this site. The graph construction encodes three distinct AST relations,
              but the trained model doesn&apos;t yet condition on edge type — this is a
              disclosed limitation and a direction for future work, not something papered
              over in the results.
            </p>
          </div>
        </Reveal>
      </section>

      <section className="mt-20">
        <Reveal>
          <h2 className="font-display text-2xl">Evaluation</h2>
        </Reveal>
        <Reveal delay={0.05}>
          <p className="measure mt-4 text-text-dim leading-relaxed">
            Three angles: in-distribution accuracy against token- and length-based
            baselines, cross-generator transfer to generators unseen in training, and
            adversarial robustness under token obfuscation and structural rewrites
            (dead-code injection, if-inversion). See{" "}
            <a href="/results" className="text-edge-structural hover:text-text">
              results
            </a>{" "}
            and{" "}
            <a href="/findings" className="text-edge-structural hover:text-text">
              findings
            </a>
            .
          </p>
        </Reveal>
      </section>
    </div>
  );
}
