import Link from "next/link";
import Hero3D from "@/components/hero/Hero3D";
import EdgeLegend from "@/components/EdgeLegend";
import Reveal from "@/components/Reveal";
import { DATASET, GNN_ROC_AUC, IN_DISTRIBUTION_TABLE } from "@/lib/content";

export default function Home() {
  const gnn = IN_DISTRIBUTION_TABLE.find((r) => r.model.startsWith("GNN"))!;

  return (
    <div>
      <section className="relative h-[92vh] min-h-[640px] w-full overflow-hidden border-b border-border-color bg-bg">
        <div className="absolute inset-0">
          <Hero3D />
        </div>
        <div className="absolute inset-0 bg-gradient-to-b from-bg/10 via-transparent to-bg pointer-events-none" />

        <div className="relative z-10 h-full mx-auto max-w-6xl px-5 sm:px-8 flex flex-col justify-end pb-20">
          <p className="font-mono text-xs text-text-dim mb-4 tracking-wide">
            {DATASET.totalPairs} matched human / machine Python function pairs: GIN over AST graphs
          </p>
          <h1 className="font-display text-[2.75rem] sm:text-6xl lg:text-7xl leading-[1.02] max-w-4xl text-text">
            Structure Over Surface
          </h1>
          <p className="measure mt-6 text-lg text-text-dim leading-relaxed">
            Detecting machine-generated Python code from the shape of its abstract syntax
            tree, not its vocabulary, comments, or formatting. Every edge in the diagram
            above is real: a graph assembling itself the same way the model sees code.
          </p>

          <div className="mt-8 flex flex-wrap items-center gap-x-8 gap-y-4">
            <Link
              href="/methodology"
              className="font-mono text-sm border border-border-color px-4 py-2.5 hover:border-edge-structural hover:text-edge-structural transition-colors"
            >
              Read the methodology →
            </Link>
            <Link
              href="/demo"
              className="font-mono text-sm text-text-dim hover:text-text transition-colors"
            >
              Try the demo →
            </Link>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-5 sm:px-8 py-24">
        <Reveal>
          <EdgeLegend className="mb-16" />
        </Reveal>

        <div className="grid sm:grid-cols-3 gap-10 sm:gap-8">
          <Reveal delay={0}>
            <div className="font-mono text-4xl text-text">{DATASET.totalPairs}</div>
            <p className="mt-2 text-sm text-text-dim measure">
              matched pairs, {DATASET.human} human-written and {DATASET.machine} generated by{" "}
              {DATASET.generatorForTraining}.
            </p>
          </Reveal>
          <Reveal delay={0.08}>
            <div className="font-mono text-4xl text-text">{gnn.accuracy.toFixed(4)}</div>
            <p className="mt-2 text-sm text-text-dim measure">
              in-distribution accuracy, docstring-free, structure alone: no tokens, no
              identifiers, no comments.
            </p>
          </Reveal>
          <Reveal delay={0.16}>
            <div className="font-mono text-4xl text-text">
              {GNN_ROC_AUC.mean.toFixed(4)}
            </div>
            <p className="mt-2 text-sm text-text-dim measure">
              ROC-AUC, five-seed mean (± {GNN_ROC_AUC.sd.toFixed(4)}).
            </p>
          </Reveal>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-5 sm:px-8 pb-28">
        <Reveal>
          <h2 className="font-display text-3xl sm:text-4xl max-w-2xl">
            This site reports what worked, what didn&apos;t, and where a simpler baseline
            beats the graph model outright.
          </h2>
          <p className="measure mt-5 text-text-dim leading-relaxed">
            The findings section covers a docstring confound that was found and corrected,
            two architectural choices that turned out not to matter, and a token-level
            model that generalizes to structural adversarial edits better than this graph
            model does. None of it is spun.
          </p>
          <Link
            href="/findings"
            className="inline-block mt-6 font-mono text-sm text-edge-flow hover:text-text transition-colors"
          >
            Read the findings →
          </Link>
        </Reveal>
      </section>
    </div>
  );
}
